logging.level.root=INFO
logging.file.name=/logs/cubetrek-logging.log
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.cache=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##coche control for web assets: 1 sec
spring.web.resources.cache.cachecontrol.max-age=1
spring.web.resources.cache.cachecontrol.cache-public=true
