###Change the profile here
spring.profiles.active=production

# ===============================
# = DATA SOURCEconnect
# ===============================
# Set here configurations for the database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSOWRD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Keep the connection alive if idle for a long time (needed in production)
spring.datasource.tomcat.test-while-idle=true
spring.datasource.tomcat.validation-query=SELECT 1
spring.jpa.open-in-view=false
# ===============================
# = JPA / HIBERNATE
# ===============================
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
spring.jpa.hibernate.ddl-auto=update


logging.pattern.dateformat=${LOGGING_DATE_FORMAT:yyyy-MM-dd HH:mm:ss.SSS,Europe/Zurich}

cubetrek.address=${CUBETREK_ADDRESS}
cubetrek.hgt.1dem=/maps/HGT_1DEM/
cubetrek.hgt.3dem=/maps/HGT/


###JavaMailSender
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.from=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_FROM}
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

#Execution Pool for Async Events
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=1000
spring.task.execution.shutdown.await-termination=true
spring.task.execution.shutdown.await-termination-period=10s
spring.task.execution.pool.allow-core-thread-timeout=false
spring.task.execution.thread-name-prefix=cubetrek-task-exec-


# Max file size.
spring.servlet.multipart.max-file-size=100MB
# Max request size.
spring.servlet.multipart.max-request-size=108MB
server.error.whitelabel.enabled=false

maptiler.api.key=${MAPTILER_API_KEY}
googlemap.api.key=${GOOGLEMAP_API_KEY}
cesium.ion.defaultAccessToken=${CESIUM_ION_ACCESS_TOKEN}

stripe.controller.enabled=${STRIPE_CONTROLLER_ENABLED}
stripe.api.key=${STRIPE_API_KEY}
stripe.price=${STRIPE_PRICE}
stripe.endpoint.secret=${STRIPE_ENDPOINT_SECRET}
stripe.endpoint.public=${STRIPE_ENDPOINT_PUBLIC}

cloudflare.turnstyle.secret=${CLOUDFLARE_TURNSTYLE_SECRET}

garmin.consumer.key=${GARMIN_CONSUMER_KEY}
garmin.consumer.secret=${GARMIN_CONSUMER_SECRET}

polar.client.id=${POLAR_CLIENT_ID}
polar.client.secret=${POLAR_CLIENT_SECRET}
polar.webhook.signature_secret_key=${POLAR_WEBHOOK_SIGNATURE_SECRET_KEY}
polar.webhook.id=${POLAR_WEBHOOK_ID}

suunto.client.id=${SUUNTO_CLIENT_ID}
suunto.primary.key=${SUUNTO_PRIMARY_KEY}
suunto.client.secret=${SUUNTO_CLIENT_SECRET}

thirdparty.clientkey.key=${THIRDPARTY_CLIENTKEY_KEY}